/* GENERATED by home-final/_build_forms.py. Do not edit.

   The download gate.

   Every case study and article PDF sits behind a lead capture form, the way it
   does on the live site: the Download button opens a modal, the reader gives a
   name and an email, and the file comes back.

   Portal 144906745, region eu1, form 300acd1e-5c44-4728-b375-f51164c018b5, read off the CTA
   that gates the download on gryd.energy.

   Mehdi, 8 September: the form is ours now rather than HubSpot's iframe embed,
   and the lead goes straight to the Forms API. That settles what the gate was
   built around for a week. There is no third party frame to read a signal out
   of, no cross origin message to authenticate and no observer guessing at what
   a renderer wrote, so the rule is the only one that was ever wanted: the API
   took the lead, with a 2xx. A failed send offers the send again and hands over
   nothing.

   Mehdi, 10 September: what a taken lead buys changed. The document no longer
   opens in the browser. The reader is told it is on the way and /api/lead posts
   it to the address they just gave, so the file lands where the lead did.

   The one case that still hands the file over on the spot is the fallback: when
   /api/lead cannot be reached the form posts to HubSpot instead, no backend has
   seen the submission and nothing will be emailed, so refusing the file there
   would take the document off a reader who gave us their details for it.

   Every word the reader sees is HubSpot's, read out of the v4 render
   definition at build time, apart from the confirmation line, which is ours
   because it describes what this site does with the lead rather than anything
   the portal holds. No consent line is drawn, because neither form carries a
   consent module in the portal and inventing one would put a claim in the
   reader's mouth the portal cannot back. */
(function () {
  var SPEC = {
  "formId": "300acd1e-5c44-4728-b375-f51164c018b5",
  "portalId": "144906745",
  "region": "eu1",
  "endpoint": "https://forms-eu1.hsforms.com/submissions/v3/integration/submit/144906745/300acd1e-5c44-4728-b375-f51164c018b5",
  "steps": [
    {
      "fields": [
        {
          "objectTypeId": "0-1",
          "name": "firstname",
          "label": "First Name",
          "type": "text",
          "required": true,
          "default": ""
        },
        {
          "objectTypeId": "0-1",
          "name": "lastname",
          "label": "Last Name",
          "type": "text",
          "required": true,
          "default": ""
        },
        {
          "objectTypeId": "0-1",
          "name": "email",
          "label": "Email",
          "type": "email",
          "required": true,
          "default": ""
        }
      ],
      "text": {
        "heading": "Download the Case Study",
        "paras": [
          "Complete the form and we'll send the case study directly to your inbox."
        ]
      },
      "progress": "number",
      "buttons": {
        "submit": "Submit"
      },
      "rail": "1/1",
      "pct": 100
    }
  ],
  "post": {
    "heading": "It's on its way to your inbox!",
    "paras": [
      "Thank you, we've sent a link to your inbox to download the case study.",
      "If you can't find it, check your junk folder or email hello@gryd.energy"
    ]
  },
  "errors": {
    "required": "Please complete this required field.",
    "email": "Email must be formatted correctly.",
    "form": "The form could not be submitted because some fields contain errors."
  }
};

  var links = Array.prototype.slice.call(document.querySelectorAll('a.btn[download]'));
  if (!links.length) { return; }

  var pending = null;   // the PDF the reader asked for
  var opener = null;    // the button to hand focus back to
  var done = false;     // the file has been released for this open
  var form = null;

  var modal = document.createElement('div');
  modal.className = 'dl-gate';
  modal.hidden = true;
  modal.innerHTML =
    '<div class="dl-scrim" data-close></div>' +
    // The form carries its own heading and standfirst, so the panel gives it
    // the paper and the close control and says nothing over the top.
    '<div class="dl-panel" role="dialog" aria-modal="true" aria-label="Download">' +
      '<button type="button" class="dl-x" data-close aria-label="Close">&#215;</button>' +
      '<div class="dl-form hs-form" id="dl-gate-form"></div>' +
      // The link is its own element under the form rather than a rewrite of
      // it, so the post submit copy the form draws stays on screen beside it.
      '<div class="dl-done" id="dl-gate-done" hidden></div>' +
    '</div>';
  document.body.appendChild(modal);

  function host() { return document.getElementById('dl-gate-form'); }
  function doneBox() { return document.getElementById('dl-gate-done'); }

  /* Which document was asked for, as the backend has to be told it: the path on
     this site, never a whole address, and the page's own title beside it. */
  function docPath() {
    if (!pending) { return ''; }
    try { return new URL(pending, window.location.href).pathname; }
    catch (e) { return ''; }
  }

  /* The confirmation. Ours, not HubSpot's, because it describes what this site
     just did with the lead. */
  function confirm(email) {
    var box = doneBox();
    if (!box) { return; }
    box.innerHTML = '';
    box.hidden = false;
    var note = document.createElement('p');
    note.className = 'dl-note';
    note.setAttribute('role', 'status');
    note.textContent = email
      ? 'Check your inbox, the PDF is on its way to ' + email
      : 'Check your inbox, the PDF is on its way to you';
    box.appendChild(note);
    note.setAttribute('tabindex', '-1');
    note.focus();
  }

  /* The file itself, under the words HubSpot's form ends on. Only the fallback
     reaches this: when the lead went to HubSpot alone, no backend saw it and
     nothing will arrive by email, so the reader is handed the file here. */
  function release() {
    if (!pending) { return; }
    var box = doneBox();
    if (!box) { return; }
    box.innerHTML = '';
    box.hidden = false;
    var a = document.createElement('a');
    a.className = 'btn';
    a.href = pending;
    a.target = '_blank';
    a.rel = 'noopener';
    a.textContent = 'Open the PDF';
    box.appendChild(a);
    a.focus();
  }

  function finish(values, via) {
    if (done) { return; }
    done = true;
    if (via === 'hubspot') { release(); return; }
    confirm(values && values.email);
  }

  function build() {
    if (form && !done) { return; }
    form = window.GrydHsForm.mount(host(), SPEC, {
      name: 'download-gate',
      source: 'gate',
      leadPayload: function () {
        return { pdf: docPath(), title: document.title };
      },
      onSuccess: finish
    });
  }

  function focusable() {
    return modal.querySelectorAll(
      'a[href], button:not([disabled]), input, select, textarea,'
      + ' [tabindex]:not([tabindex="-1"])');
  }

  function open(href, from) {
    pending = href;
    opener = from;
    done = false;
    if (doneBox()) { doneBox().hidden = true; }
    if (host()) { host().hidden = false; }
    modal.hidden = false;
    document.documentElement.classList.add('dl-open');
    build();
    var x = modal.querySelector('.dl-x');
    if (x) { x.focus(); }
  }

  function close() {
    modal.hidden = true;
    document.documentElement.classList.remove('dl-open');
    if (opener) { opener.focus(); opener = null; }
  }

  modal.addEventListener('click', function (e) {
    if (e.target.hasAttribute('data-close')) { close(); }
  });

  /* Escape closes the gate, and Tab is held inside it while it is up. */
  document.addEventListener('keydown', function (e) {
    if (modal.hidden) { return; }
    if (e.key === 'Escape') { close(); return; }
    if (e.key !== 'Tab') { return; }
    var items = focusable();
    if (!items.length) { return; }
    var first = items[0], last = items[items.length - 1];
    var here = document.activeElement;
    if (!modal.contains(here)) { e.preventDefault(); first.focus(); return; }
    if (e.shiftKey && here === first) { e.preventDefault(); last.focus(); }
    else if (!e.shiftKey && here === last) { e.preventDefault(); first.focus(); }
  });

  links.forEach(function (a) {
    a.addEventListener('click', function (e) {
      e.preventDefault();
      open(a.href, a);
    });
  });
})();
