/* GENERATED by home-final/_build_draft.py. Do not edit.

   The FAQ index. A click travels to its group rather than snapping to it, the
   group lands clear of the pill nav, and the index says which group the reader
   is in whether they clicked or scrolled there. */
(function () {
  var nav = document.querySelector('.faq-index');
  if (!nav) return;
  var links = [].slice.call(nav.querySelectorAll('a[href^="#"]'));
  if (!links.length) return;
  var reduced = matchMedia('(prefers-reduced-motion: reduce)');

  /* The pill is fixed and can be tucked away mid scroll, so its clearance is
     measured while it is on screen and kept. GAP is the breathing space under
     the pill. */
  var GAP = 6;
  var clearance = 120;
  function measure() {
    var pill = document.querySelector('.dnav');
    if (!pill) return;
    var r = pill.getBoundingClientRect();
    if (!r.height) return;   // tucked, so the last good reading stands
    clearance = Math.round(r.bottom + GAP);
    document.documentElement.style.setProperty('--faq-anchor', clearance + 'px');
  }
  measure();
  addEventListener('resize', measure);
  addEventListener('load', measure);

  function target(a) {
    var id = a.getAttribute('href').slice(1);
    return id ? document.getElementById(id) : null;
  }

  function mark(a) {
    links.forEach(function (l) {
      if (l === a) l.setAttribute('aria-current', 'true');
      else l.removeAttribute('aria-current');
    });
  }

  /* A group whose questions are all shut is a row of titles with nothing under
     it, so arriving opens the first one. home-ui.js owns the accordion, and a
     click on the button is the way to ask it for that. */
  function reveal(sec) {
    var open = sec.querySelector('.faq-q[aria-expanded="true"]');
    if (open) return;
    var first = sec.querySelector('.faq-q');
    if (first) first.click();
  }

  links.forEach(function (a) {
    a.addEventListener('click', function (e) {
      var sec = target(a);
      if (!sec) return;
      e.preventDefault();
      measure();
      mark(a);
      reveal(sec);
      var y = sec.getBoundingClientRect().top + scrollY - clearance;
      scrollTo({ top: Math.max(0, y), behavior: reduced.matches ? 'auto' : 'smooth' });
      if (history.replaceState) history.replaceState(null, '', a.getAttribute('href'));
    });
  });

  /* Scrolling marks the index too. The band starts under the pill and is one
     line tall, so the current group is the last one whose head has passed it. */
  if (!('IntersectionObserver' in window)) return;
  var seen = {};
  var io = new IntersectionObserver(function (entries) {
    entries.forEach(function (en) { seen[en.target.id] = en.isIntersecting; });
    var pick = null;
    links.forEach(function (l) {
      var sec = target(l);
      if (sec && seen[sec.id]) pick = pick || l;
    });
    if (pick) mark(pick);
  }, { rootMargin: '-' + clearance + 'px 0px -55% 0px', threshold: 0 });
  [].forEach.call(document.querySelectorAll('.faq-set'), function (s) { io.observe(s); });
})();
