/* GENERATED by home-final/_build_draft.py. Do not edit. */
(function () {
  var track = document.querySelector("[data-batt]");
  if (!track) return;

  var small = window.matchMedia("(max-width: 900px)").matches;
  var calm = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  /* Both rest states are drawn by the sheet, and neither wants the clip. No
     source is attached in either, so nothing is ever fetched for them. */
  if (small || calm) return;

  var steps = track.querySelectorAll(".step");
  var STEPS = steps.length || 1;
  /* The steps divide the loop between them, as the n+1 edges of n steps. The
     band runs 40, 40, 20: the two long moves take most of the clip and the
     night step holds the last fifth, which is the part already at rest. Same
     cut the scrub used, so the copy still lands with the light it describes. */
  var CUTS = (function () {
    var raw = (track.dataset.bands || "").split(",")
      .map(parseFloat).filter(function (v) { return !isNaN(v); });
    if (raw.length === STEPS + 1) return raw;
    var even = [];
    for (var k = 0; k <= STEPS; k++) even.push(k / STEPS);
    return even;
  }());

  var visual = track.querySelector(".visual");
  var video = track.querySelector(".clip");
  var armed = false, ready = false, near = false, shown = -1;

  function clamp(v) { return v < 0 ? 0 : v > 1 ? 1 : v; }
  function smooth(p) { p = clamp(p); return p * p * (3 - 2 * p); }

  /* p on 0..1 remapped onto 0..STEPS, so a step's own share of the loop reads
     as one whole unit whatever width that share is. */
  function rawOf(p) {
    for (var k = 0; k < STEPS; k++) {
      if (p < CUTS[k + 1] || k === STEPS - 1) {
        var w = CUTS[k + 1] - CUTS[k] || 1;
        return k + clamp((p - CUTS[k]) / w);
      }
    }
    return STEPS;
  }

  /* The clip is fetched when the band is within a viewport of the reader and
     not before, so it cannot compete with first paint. Both sources are
     attached: Blink ignores the media attribute on source, so the choice is
     made by type alone and the webm is offered first for Firefox. */
  function attach() {
    if (armed) return;
    armed = true;
    [[video.dataset.srcWebm, "video/webm"],
     [video.dataset.srcMp4, "video/mp4"]].forEach(function (pair) {
      if (!pair[0]) return;
      var s = document.createElement("source");
      s.src = pair[0];
      s.type = pair[1];
      video.appendChild(s);
    });
    video.load();
  }

  /* The poster covers the frame until the clip has decoded something it can
     paint, then the two swap and the loop runs. */
  function arm() {
    if (ready) return;
    ready = true;
    visual.classList.add("ready");
    play();
  }

  function play() {
    if (!ready || !near) return;
    var pr = video.play();
    if (pr && pr.catch) pr.catch(function () {});
  }

  video.muted = true;
  video.loop = true;
  video.playsInline = true;
  video.addEventListener("loadeddata", arm);
  video.addEventListener("canplay", arm);

  /* A band the reader has scrolled past is a decode nobody is watching, so the
     loop is held off screen and picked up again on the way back. */
  if ("IntersectionObserver" in window) {
    new IntersectionObserver(function (entries) {
      entries.forEach(function (e) {
        if (e.isIntersecting) { near = true; attach(); play(); }
        else if (near) { near = false; try { video.pause(); } catch (err) {} }
      });
    }, {rootMargin: "100% 0px"}).observe(track);
  } else {
    near = true;
    attach();
  }

  /* Which rung the loop is on. Read off the clip's own playhead rather than
     off a timer of our own, so the copy cannot drift away from the picture
     however the browser schedules the decode. */
  function draw() {
    var d = video.duration;
    var p = (ready && d) ? clamp(video.currentTime / d) : 0;
    track.style.setProperty("--p", p.toFixed(4));

    var raw = rawOf(p);
    var i = Math.min(STEPS - 1, Math.floor(raw));
    if (i !== shown) {
      shown = i;
      track.dataset.step = i;
    }
    /* Every step stays readable: the loop moves the emphasis, not the text.
       The weight sits on a triangular window centred on the step's own share,
       so no rung is ever dimmer than 45 per cent. */
    for (var s = 0; s < steps.length; s++) {
      var dist = Math.abs(raw - (s + 0.5));
      steps[s].style.setProperty(
        "--o", (1 - 0.55 * smooth(clamp((dist - 0.5) / 0.5))).toFixed(3));
      steps[s].toggleAttribute("data-on", s === i);
    }
  }

  function tick() {
    draw();
    requestAnimationFrame(tick);
  }

  /* The gates and the screenshot harness read the loop's own position rather
     than keeping a second copy of the arithmetic. */
  window.battProgress = function () {
    var d = video.duration;
    return (ready && d) ? clamp(video.currentTime / d) : 0;
  };
  /* Park the loop at a fraction of itself, so a still can be taken of a known
     beat without waiting for the clip to come round to it. */
  window.battSeek = function (f) {
    if (!video.duration) return false;
    video.currentTime = clamp(f) * video.duration;
    draw();
    return true;
  };

  draw();
  requestAnimationFrame(tick);
})();
