/* GENERATED by home-final/_build_draft.py. Do not edit.

   The band's player. It plays the clip, pauses it off screen, and touches
   nothing else: the ladder beside it is CSS alone and no line here reads or
   writes a rung, a step or a progress. */
(function () {
  var track = document.querySelector("[data-batt]");
  if (!track) return;

  /* The reduced motion rest state is drawn by the sheet and does not want the
     clip, so no source is attached and nothing is ever fetched for it. */
  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

  var visual = track.querySelector(".visual");
  var video = track.querySelector(".clip");
  if (!visual || !video) return;

  var armed = false, ready = false, near = false;

  /* The clip is fetched when the band is within a viewport of the reader and
     not before, so it cannot compete with first paint. Both sources are
     attached: Blink ignores the media attribute on source, so the choice is
     made by type alone and the webm is offered first for Firefox. */
  function attach() {
    if (armed) return;
    armed = true;
    [[video.dataset.srcWebm, "video/webm"],
     [video.dataset.srcMp4, "video/mp4"]].forEach(function (pair) {
      if (!pair[0]) return;
      var s = document.createElement("source");
      s.src = pair[0];
      s.type = pair[1];
      video.appendChild(s);
    });
    video.load();
  }

  function play() {
    if (!ready || !near) return;
    var pr = video.play();
    if (pr && pr.catch) pr.catch(function () {});
  }

  /* The poster covers the frame until the clip has decoded something it can
     paint, then the two swap and the loop runs. */
  function arm() {
    if (!ready) {
      ready = true;
      visual.classList.add("ready");
    }
    play();
  }

  video.muted = true;
  video.loop = true;
  video.playsInline = true;
  video.addEventListener("loadeddata", arm);
  video.addEventListener("canplay", arm);

  /* A band the reader has scrolled past is a decode nobody is watching, so the
     loop is held off screen and picked up again on the way back. */
  if ("IntersectionObserver" in window) {
    new IntersectionObserver(function (entries) {
      entries.forEach(function (e) {
        if (e.isIntersecting) { near = true; attach(); play(); }
        else if (near) { near = false; try { video.pause(); } catch (err) {} }
      });
    }, {rootMargin: "100% 0px"}).observe(track);
  } else {
    near = true;
    attach();
  }
}());
