/* GENERATED by home-final/_build_draft.py. Do not edit. */
(function () {
  var track = document.querySelector("[data-batt]");
  if (!track) return;

  var small = window.matchMedia("(max-width: 900px)").matches;
  var calm = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  /* Both rest states are drawn by the sheet, and neither wants the clip. No
     source is attached in either, so nothing is ever fetched for them. */
  if (small || calm) return;

  var STEPS = 3;
  /* A browser paints whole frames, so a seek finer than one frame is a decode
     nobody sees. The clip runs at 24fps; a thirtieth of a second is under one
     frame and still kills the jitter of seeking on every tick. */
  var SEEK_EPS = 1 / 30;

  var steps = track.querySelectorAll(".step");
  var rails = track.querySelectorAll(".rail i");
  var visual = track.querySelector(".visual");
  var video = track.querySelector(".clip");
  var last = -1, ready = false, armed = false;

  function clamp(v) { return v < 0 ? 0 : v > 1 ? 1 : v; }
  /* Smoothstep rather than an expo. The label crossfades have to be continuous
     through the step boundary in both directions, and an expo.out is steep at
     its own start, which reads as a snap when it is scrubbed. */
  function smooth(p) { p = clamp(p); return p * p * (3 - 2 * p); }

  /* The clip is fetched when the band is within a viewport of the reader and
     not before, so it cannot compete with first paint. Both sources are
     attached: Blink ignores the media attribute on source, so the choice is
     made by type alone and the webm is offered first for Firefox. */
  function attach() {
    if (armed) return;
    armed = true;
    [[video.dataset.srcWebm, "video/webm"],
     [video.dataset.srcMp4, "video/mp4"]].forEach(function (pair) {
      if (!pair[0]) return;
      var s = document.createElement("source");
      s.src = pair[0];
      s.type = pair[1];
      video.appendChild(s);
    });
    video.load();
  }

  /* The clip has to be decoded and holding a frame before the band pins, or
     the first seek paints black. Playing muted for a moment and pausing is the
     one request every browser honours as a request to decode; the poster
     covers the frame until it lands. */
  function arm() {
    if (ready) return;
    var p = video.play();
    var settle = function () {
      try { video.pause(); } catch (e) {}
      video.currentTime = 0;
      ready = true;
      visual.classList.add("ready");
    };
    if (p && p.then) { p.then(settle).catch(settle); } else { settle(); }
  }

  video.muted = true;
  video.playsInline = true;
  video.addEventListener("loadeddata", arm);
  video.addEventListener("canplay", arm);

  if ("IntersectionObserver" in window) {
    new IntersectionObserver(function (entries, obs) {
      if (entries.some(function (e) { return e.isIntersecting; })) {
        attach();
        obs.disconnect();
      }
    }, {rootMargin: "100% 0px"}).observe(track);
  } else {
    attach();
  }

  function draw() {
    var box = track.getBoundingClientRect();
    var span = box.height - window.innerHeight;
    var p = span > 0 ? clamp(-box.top / span) : 0;
    track.style.setProperty("--p", p.toFixed(4));

    var raw = p * STEPS;

    /* Labels. Each fades up over the first fifth of its own third; the first is
       held in from the top so the band pins with a readable label rather than
       with a hole where one will be, and the last never fades out so the band
       rests on it. */
    for (var s = 0; s < steps.length; s++) {
      var l = clamp(raw - s);
      var inp = s === 0 ? 1 : smooth(l / 0.20);
      var outp = s === STEPS - 1 ? 0 : smooth((l - 0.84) / 0.16);
      steps[s].style.setProperty("--o", (inp * (1 - outp)).toFixed(3));
      steps[s].style.setProperty("--y", ((1 - inp) * 18 - outp * 14).toFixed(1) + "px");
    }
    /* The dashes take the raw progress with no easing at all, so each grows at
       exactly the rate the page is being scrolled. */
    for (var r = 0; r < rails.length; r++) {
      rails[r].style.setProperty("--f", clamp(raw - r).toFixed(3));
    }
    track.dataset.step = Math.min(STEPS - 1, Math.floor(raw));

    /* The day to evening move runs across the whole band rather than inside one
       step, with a short flat lead in and lead out so both end states can be
       held and read. */
    var lit = smooth((p - 0.08) / 0.80);
    track.style.setProperty("--lit", lit.toFixed(4));

    if (ready && video.duration) {
      var want = lit * video.duration;
      if (want > video.duration - 0.05) want = video.duration - 0.05;
      if (Math.abs(want - video.currentTime) > SEEK_EPS) video.currentTime = want;
    }
  }

  /* A persistent loop rather than a scroll listener. Momentum scrolling
     delivers scroll events in bursts and a seek issued from a burst lands late;
     polling the box every frame keeps the picture on the same clock as the
     scroll. The compare guard means an idle page does no layout work beyond the
     one read. */
  function tick() {
    var box = track.getBoundingClientRect();
    if (box.top !== last) { last = box.top; draw(); }
    requestAnimationFrame(tick);
  }
  draw();
  requestAnimationFrame(tick);
})();
