/* GENERATED by home-final/_build_draft.py. Do not edit. */
(function () {
  var track = document.querySelector("[data-batt]");
  if (!track) return;

  var small = window.matchMedia("(max-width: 900px)").matches;
  var calm = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  /* Both rest states are drawn by the sheet, and neither wants the clip. No
     source is attached in either, so nothing is ever fetched for them. */
  if (small || calm) return;

  var STEPS = 3;
  /* A browser paints whole frames, so a seek finer than one frame is a decode
     nobody sees. The clip runs at 24fps; a thirtieth of a second is under one
     frame and still kills the jitter of seeking on every tick. */
  var SEEK_EPS = 1 / 30;
  /* The nav pill ends at 72px. Below this the band would be held under it. */
  var MIN_TOP = 88;

  var card = track.querySelector(".pin-card");
  var steps = track.querySelectorAll(".step");
  var visual = track.querySelector(".visual");
  var video = track.querySelector(".clip");
  var last = null, ready = false, armed = false;
  var span = 1, pinTop = MIN_TOP;

  function clamp(v) { return v < 0 ? 0 : v > 1 ? 1 : v; }
  /* Smoothstep rather than an expo. The weights have to be continuous through
     the step boundary in both directions, and an expo.out is steep at its own
     start, which reads as a snap when it is scrubbed. */
  function smooth(p) { p = clamp(p); return p * p * (3 - 2 * p); }

  /* The band is centred in the window for the whole of the scrub, which means
     the sticky offset is half of what the window's height leaves over. That is
     two numbers the sheet does not have, so it is written from here, and the
     track is measured from the band rather than stated in screens: the runway
     is the band's own height and one step of the three more. */
  function measure() {
    track.style.height = "";
    var h = card.getBoundingClientRect().height;
    pinTop = Math.max(MIN_TOP, Math.round((window.innerHeight - h) / 2));
    track.style.setProperty("--pin-top", pinTop + "px");
    span = Math.max(1, Math.round(h * (4 / 3)));
    track.style.height = Math.round(h + span) + "px";
  }

  function progress() {
    var box = track.getBoundingClientRect();
    return clamp((-box.top + pinTop) / span);
  }

  /* The clip is fetched when the band is within a viewport of the reader and
     not before, so it cannot compete with first paint. Both sources are
     attached: Blink ignores the media attribute on source, so the choice is
     made by type alone and the webm is offered first for Firefox. */
  function attach() {
    if (armed) return;
    armed = true;
    [[video.dataset.srcWebm, "video/webm"],
     [video.dataset.srcMp4, "video/mp4"]].forEach(function (pair) {
      if (!pair[0]) return;
      var s = document.createElement("source");
      s.src = pair[0];
      s.type = pair[1];
      video.appendChild(s);
    });
    video.load();
  }

  /* The clip has to be decoded and holding a frame before the band pins, or
     the first seek paints black. Playing muted for a moment and pausing is the
     one request every browser honours as a request to decode; the poster
     covers the frame until it lands. */
  function arm() {
    if (ready) return;
    var p = video.play();
    var settle = function () {
      try { video.pause(); } catch (e) {}
      video.currentTime = 0;
      ready = true;
      visual.classList.add("ready");
      /* The loop only draws when the band has moved, so a clip that finishes
         decoding after the reader has already stopped inside the band would
         sit on its first frame until the next scroll. Draw once here. */
      last = null;
      draw();
    };
    if (p && p.then) { p.then(settle).catch(settle); } else { settle(); }
  }

  video.muted = true;
  video.playsInline = true;
  video.addEventListener("loadeddata", arm);
  video.addEventListener("canplay", arm);

  if ("IntersectionObserver" in window) {
    new IntersectionObserver(function (entries, obs) {
      if (entries.some(function (e) { return e.isIntersecting; })) {
        attach();
        obs.disconnect();
      }
    }, {rootMargin: "100% 0px"}).observe(track);
  } else {
    attach();
  }

  function draw() {
    var p = progress();
    track.style.setProperty("--p", p.toFixed(4));

    var raw = p * STEPS;
    var i = Math.min(STEPS - 1, Math.floor(raw));

    /* Every step stays readable: the scrub moves the emphasis, not the text.
       The weight sits on a triangular window centred on the step's own third,
       so the band pins with its first step already at full weight rather than
       with three dim rows and nothing to read. */
    for (var s = 0; s < steps.length; s++) {
      var d = Math.abs(raw - (s + 0.5));
      steps[s].style.setProperty(
        "--o", (1 - 0.55 * smooth(clamp((d - 0.5) / 0.5))).toFixed(3));
      steps[s].toggleAttribute("data-on", s === i);
    }
    track.dataset.step = i;

    /* The day to evening move runs across the whole band rather than inside one
       step, with a short flat lead in and lead out so both end states can be
       held and read. */
    var lit = smooth((p - 0.08) / 0.80);
    track.style.setProperty("--lit", lit.toFixed(4));

    if (ready && video.duration) {
      var want = lit * video.duration;
      if (want > video.duration - 0.05) want = video.duration - 0.05;
      if (Math.abs(want - video.currentTime) > SEEK_EPS) video.currentTime = want;
    }
  }

  /* A persistent loop rather than a scroll listener. Momentum scrolling
     delivers scroll events in bursts and a seek issued from a burst lands late;
     polling the box every frame keeps the picture on the same clock as the
     scroll. The compare guard means an idle page does no layout work beyond the
     one read. */
  function tick() {
    var top = track.getBoundingClientRect().top;
    if (top !== last) { last = top; draw(); }
    requestAnimationFrame(tick);
  }

  function remeasure() { measure(); last = null; draw(); }

  /* The screenshot harness and the gates need the document scroll position of a
     given progress, and it has to be the driver's own arithmetic rather than a
     second copy of it, or the shots and the page disagree about what half way
     through the band means. */
  window.battTarget = function (p) {
    var zero = window.scrollY + track.getBoundingClientRect().top - pinTop;
    return Math.round(zero + p * span);
  };
  window.battProgress = progress;

  measure();
  draw();
  window.addEventListener("resize", remeasure);
  /* Web fonts land after first paint and change the copy column's height, which
     changes both the centre and the runway. */
  if (document.fonts && document.fonts.ready) {
    document.fonts.ready.then(remeasure);
  }
  requestAnimationFrame(tick);
})();
