/* GENERATED by home-final/_build_draft.py. Do not edit.

   The Get in touch modal, on the same embed pattern as the hub's download
   gate: the HubSpot script is asked for on the first open and never before,
   and hbspt.forms.create draws the form into the panel. */
(function () {
  var PORTAL = "144906745";
  var FORM = "8ce7ddd3-fe9e-4433-8741-077aae8f72c3";
  var REGION = "eu1";
  var EMBED = "https://js-eu1.hsforms.net/forms/embed/v2.js";

  var modal = document.getElementById("contactModal");
  if (!modal) return;
  var panel = modal.querySelector(".gc-panel");
  var opener = null, built = false;

  function build() {
    if (built) return;
    built = true;
    var s = document.createElement("script");
    s.src = EMBED;
    s.onload = function () {
      if (!window.hbspt) return;
      window.hbspt.forms.create({
        region: REGION, portalId: PORTAL, formId: FORM,
        target: "#gc-contact-form"
      });
    };
    s.onerror = function () {
      document.getElementById("gc-contact-form").innerHTML =
        '<p class="gc-note">The form could not load. Email '
        + '<a href="mailto:hello@gryd.energy">hello@gryd.energy</a> '
        + 'and we will pick it up from there.</p>';
    };
    document.head.appendChild(s);
  }

  function focusable() {
    return panel.querySelectorAll(
      'a[href], button, input, select, textarea, [tabindex]:not([tabindex="-1"])');
  }

  function open(trigger) {
    opener = trigger || document.activeElement;
    modal.hidden = false;
    document.documentElement.style.overflow = "hidden";
    build();
    var x = panel.querySelector(".gc-close");
    if (x) x.focus();
  }

  function close() {
    modal.hidden = true;
    document.documentElement.style.overflow = "";
    if (opener && opener.focus) opener.focus();
    opener = null;
  }

  document.addEventListener("click", function (e) {
    var o = e.target.closest("[data-contact-open]");
    if (o) { e.preventDefault(); open(o); return; }
    if (e.target.closest("[data-contact-close]")) { e.preventDefault(); close(); }
  });

  /* A dialog that cannot be left by keyboard is a dialog that traps the
     reader, so Escape closes it and Tab is kept inside it while it is up. */
  document.addEventListener("keydown", function (e) {
    if (modal.hidden) return;
    if (e.key === "Escape") { close(); return; }
    if (e.key !== "Tab") return;
    var items = focusable();
    if (!items.length) return;
    var first = items[0], last = items[items.length - 1];
    if (e.shiftKey && document.activeElement === first) {
      e.preventDefault(); last.focus();
    } else if (!e.shiftKey && document.activeElement === last) {
      e.preventDefault(); first.focus();
    }
  });
})();
