/* GENERATED by home-final/_build_draft.py. Do not edit.

   The Get in touch modal. The form inside it is the site's own, drawn by
   assets/hs-form.js from HubSpot's render definition and posted to the Forms
   API. Nothing is fetched from a third party at any point, so the page pays
   nothing for a form nobody has opened and the console stays ours. */
(function () {
  var SPEC = {
  "formId": "8ce7ddd3-fe9e-4433-8741-077aae8f72c3",
  "portalId": "144906745",
  "region": "eu1",
  "endpoint": "https://forms-eu1.hsforms.com/submissions/v3/integration/submit/144906745/8ce7ddd3-fe9e-4433-8741-077aae8f72c3",
  "steps": [
    {
      "fields": [
        {
          "objectTypeId": "0-1",
          "name": "firstname",
          "label": "First Name",
          "type": "text",
          "required": true,
          "default": ""
        },
        {
          "objectTypeId": "0-1",
          "name": "lastname",
          "label": "Last Name",
          "type": "text",
          "required": true,
          "default": ""
        },
        {
          "objectTypeId": "0-1",
          "name": "email",
          "label": "Email",
          "type": "email",
          "required": true,
          "default": ""
        }
      ],
      "text": {
        "heading": "Contact Us",
        "paras": [
          "We'd love to hear from you! Please fill out the form and we'll get back to you as soon as possible."
        ]
      },
      "progress": "percentage",
      "buttons": {
        "next": "Next"
      },
      "rail": "50%",
      "pct": 50
    },
    {
      "fields": [
        {
          "objectTypeId": "0-1",
          "name": "phone",
          "label": "Phone Number",
          "type": "tel",
          "required": false,
          "default": "+44"
        },
        {
          "objectTypeId": "0-1",
          "name": "message",
          "label": "Message",
          "type": "textarea",
          "required": false,
          "default": ""
        }
      ],
      "text": {
        "heading": "Contact Us",
        "paras": [
          "We'd love to hear from you! Please fill out the form and we'll get back to you as soon as possible."
        ]
      },
      "progress": "percentage",
      "buttons": {
        "previous": "Previous",
        "submit": "Submit"
      },
      "rail": "100%",
      "pct": 100
    }
  ],
  "post": {
    "heading": "Form submitted",
    "paras": [
      "Thank you, we'll be in touch soon."
    ]
  },
  "errors": {
    "required": "Please complete this required field.",
    "email": "Email must be formatted correctly.",
    "form": "The form could not be submitted because some fields contain errors."
  }
};

  var modal = document.getElementById("contactModal");
  if (!modal) return;
  var panel = modal.querySelector(".gc-panel");
  var host = document.getElementById("gc-contact-form");
  var opener = null, form = null, finished = false;

  function build() {
    if (form && !finished) return;
    finished = false;
    form = window.GrydHsForm.mount(host, SPEC, {
      name: "contact",
      onSuccess: function () { finished = true; }
    });
  }

  function focusable() {
    return panel.querySelectorAll(
      'a[href], button:not([disabled]), input, select, textarea,'
      + ' [tabindex]:not([tabindex="-1"])');
  }

  function open(trigger) {
    opener = trigger || document.activeElement;
    modal.hidden = false;
    document.documentElement.style.overflow = "hidden";
    build();
    var x = panel.querySelector(".gc-close");
    if (x) x.focus();
  }

  function close() {
    modal.hidden = true;
    document.documentElement.style.overflow = "";
    if (opener && opener.focus) opener.focus();
    opener = null;
  }

  document.addEventListener("click", function (e) {
    var o = e.target.closest("[data-contact-open]");
    if (o) { e.preventDefault(); open(o); return; }
    if (e.target.closest("[data-contact-close]")) { e.preventDefault(); close(); }
  });

  /* A dialog that cannot be left by keyboard is a dialog that traps the
     reader, so Escape closes it and Tab is kept inside it while it is up. The
     fields are this document's own now, so the whole cycle is reachable from
     here: Close, then every field in order, then Back and Send, then Close
     again. */
  document.addEventListener("keydown", function (e) {
    if (modal.hidden) return;
    if (e.key === "Escape") { close(); return; }
    if (e.key !== "Tab") return;
    var items = focusable();
    if (!items.length) return;
    var first = items[0], last = items[items.length - 1];
    var here = document.activeElement;
    if (!panel.contains(here)) { e.preventDefault(); first.focus(); return; }
    if (e.shiftKey && here === first) {
      e.preventDefault(); last.focus();
    } else if (!e.shiftKey && here === last) {
      e.preventDefault(); first.focus();
    }
  });

  document.addEventListener("focusin", function (e) {
    if (modal.hidden) return;
    if (panel.contains(e.target)) return;
    var items = focusable();
    if (items.length) items[0].focus();
  });
})();
