/* GENERATED by home-final/_build_draft.py. Do not edit. */
(function () {
  var rail = document.querySelector('.a-quotes .q-rail');
  if (!rail) return;
  var calm = window.matchMedia && matchMedia('(prefers-reduced-motion: reduce)');
  if (calm && calm.matches) return;

  var cards = [].slice.call(rail.querySelectorAll('.qc'));
  if (!cards.length) return;

  /* The band is a share of the card, not a fixed number of pixels. A card here
     is around 500px wide, so a 60px fade would leave one sitting half clipped at
     full strength for most of its exit, which is the cut Scott was reading. At
     the card's full width a card starts going the moment the column reaches it
     and is gone by the time it has passed: its opacity is the share of it still
     on the rail, so there is never a solid edge to read as a cut. */
  var BAND = 1;
  var LIFT = 8;    /* how far it drops out of line while it goes */
  var live = false;
  var ticking = false;

  function frame() {
    ticking = false;
    if (!live) return;
    var r = rail.getBoundingClientRect();
    for (var i = 0; i < cards.length; i++) {
      var c = cards[i];
      var b = c.getBoundingClientRect();
      /* How much of the card is still on the rail, at whichever edge it is
         nearest: the lower of the two, so a card in the middle is solid and one
         at either end is on its way. */
      var band = b.width * BAND || 1;
      var leaving = (b.right - r.left) / band;
      var entering = (r.right - b.left) / band;
      var k = Math.min(1, Math.max(0, Math.min(leaving, entering)));
      /* Squared, not linear. A card an eighth of the way past the column edge is
         seven eighths opaque on a straight ramp, and seven eighths of a card
         with a slice off it still reads as a slice. Squaring pulls the strength
         out of it as soon as the edge reaches it and lets the middle of the rail
         stay solid. */
      var e = k * k;
      c.style.opacity = e;
      c.style.transform = e < 1 ? 'translateY(' + ((1 - e) * LIFT).toFixed(2) + 'px)' : '';
    }
    ticking = true;
    requestAnimationFrame(frame);
  }

  /* The strip is one section of a long page, and the rects are only worth
     taking while it is on screen. */
  if ('IntersectionObserver' in window) {
    new IntersectionObserver(function (entries) {
      live = entries[0].isIntersecting;
      if (live && !ticking) { ticking = true; requestAnimationFrame(frame); }
    }, {rootMargin: '120px'}).observe(rail);
  } else {
    live = true;
    ticking = true;
    requestAnimationFrame(frame);
  }
})();