/* GENERATED by home-final/_build_draft.py. Do not edit. */
(function () {
  var SMALL = 900;

  function attach(video) {
    if (video.dataset.showcaseReady) return;
    var small = window.matchMedia("(max-width: " + (SMALL - 1) + "px)").matches;
    var list = small
      ? [[video.dataset.srcSmall, "video/mp4"]]
      : [[video.dataset.srcWebm, "video/webm"], [video.dataset.srcMp4, "video/mp4"]];
    list.forEach(function (pair) {
      if (!pair[0]) return;
      var source = document.createElement("source");
      source.src = pair[0];
      source.type = pair[1];
      video.appendChild(source);
    });
    video.dataset.showcaseReady = "1";
    video.load();
  }

  /* Older engines return nothing from play(), so calling .catch on the result
     throws and takes the rest of the start loop with it. */
  function play(video) {
    var p;
    try { p = video.play(); } catch (err) { return; }
    if (p && typeof p.catch === "function") p.catch(function () {});
  }

  function watch(video) {
    if (!("IntersectionObserver" in window)) {
      // no observer means no cue to attach on, so the sources go on now:
      // without them play() has nothing to play.
      attach(video);
      play(video);
      return;
    }
    var seen = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (entry.isIntersecting) {
          attach(video);
          play(video);
        } else if (!video.paused) {
          video.pause();
        }
      });
    }, {rootMargin: "120px 0px", threshold: 0});
    seen.observe(video);
  }

  function start() {
    var videos = [].slice.call(document.querySelectorAll("[data-showcase-video]"));
    var still = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    videos.forEach(function (video) {
      video.muted = true;
      if (still) {
        /* poster only: no source is attached, so nothing is ever fetched */
        video.removeAttribute("autoplay");
        video.autoplay = false;
        video.dataset.showcaseStill = "1";
        return;
      }
      watch(video);
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", start);
  } else {
    start();
  }
})();
