/* GENERATED by home-final/_build_draft.py. Do not edit. */
(function () {
  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
  var pin = document.getElementById("battPin");
  var sec = document.getElementById("battery");
  if (!pin || !sec) return;
  document.documentElement.classList.add("js");

  var rows = [].slice.call(sec.querySelectorAll(".facts div"));
  var counter = rows[0].querySelector("strong");
  var FINAL = counter.textContent;              /* "70%+", restored exactly at the end */

  /* The two written facts are split into words here rather than in the markup,
     so the page on disk keeps each label as one text node and the copy cannot
     drift from _content. The separating space stays a text node between the
     spans: inside an inline block it would be collapsed away and the words
     would run together. */
  rows.slice(1).forEach(function (row) {
    [].slice.call(row.querySelectorAll("strong, span")).forEach(function (el) {
      var words = el.textContent.split(" ");
      el.textContent = "";
      words.forEach(function (w, i) {
        if (i) el.appendChild(document.createTextNode(" "));
        var s = document.createElement("span");
        s.className = "word";
        s.textContent = w;
        el.appendChild(s);
      });
    });
  });
  var words = [].slice.call(sec.querySelectorAll(".word"));

  /* Every scroll gets a frame, not only the scrolls made while the wrapper is
     on screen. Gating the work on the wrapper intersecting looks like the
     cheaper thing to do and is wrong at both ends: a reader who flings from
     above the band to below it in one throw crosses it without the observer
     ever reporting a change, and the band is left at whatever it was last set
     to, a figure at nought and half a sentence written. What is gated instead
     is the writing. The frame reads one rectangle, and touches the document
     only when the state it computes differs from the state already on it, so a
     scroll anywhere else on the page costs a read and nothing more. */
  var queued = false, lastShown = -1, lastStat = null;
  new IntersectionObserver(frame).observe(pin);

  function frame() {
    queued = false;
    var travel = pin.offsetHeight - window.innerHeight;
    var p = travel > 0
      ? Math.max(0, Math.min(1, -pin.getBoundingClientRect().top / travel))
      : 1;

    /* the count owns the first half of the pin, the writing the rest */
    var c = Math.max(0, Math.min(1, p / 0.5));
    var stat = c >= 1 ? FINAL : Math.round(c * 70) + "%+";
    if (stat !== lastStat) { counter.textContent = stat; lastStat = stat; }
    rows[0].classList.toggle("live", p > 0.02);

    var w = Math.max(0, Math.min(1, (p - 0.42) / 0.46));
    var shown = Math.round(w * words.length);
    if (shown !== lastShown) {
      words.forEach(function (el, i) { el.classList.toggle("on", i < shown); });
      lastShown = shown;
    }
    rows[1].classList.toggle("live", p > 0.42);
    rows[2].classList.toggle("live", p > 0.66);
  }

  addEventListener("scroll", function () {
    if (!queued) { queued = true; requestAnimationFrame(frame); }
  }, { passive: true });
  addEventListener("resize", frame, { passive: true });
  frame();
})();
